### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by MarqRazz** [ros2-gbp/ompl-release#1]
Hello ompl-release team.

I would like to volunteer myself (@MarqRazz) and @JafarAbdi to help maintain the release of OMPL to ROS2. I have [open PR's to MoveIt](https://github.com/moveit/moveit2/pull/2994) that require updates from this package and we would like to help share this workload and keep this package up to date.

Please let me know if you need any additional information or help with this process.
Thanks
Marq Rasmussen

**Comment by mamoll** [comment]
Thanks @MarqRazz!

I fully support this, but don't seem to have admin rights to add @MarqRazz and @JafarAbdi to the team. @Yadunund, is this something you can do?

**Comment by clalancette** [comment]
> I fully support this, but don't seem to have admin rights to add @MarqRazz and @JafarAbdi to the team. @Yadunund, is this something you can do?

In order to do this, you'll need to submit an issue/PR to https://github.com/ros2-gbp/ros2-gbp-github-org/ , adding the people you want to the correct group (I guess it will be https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/ompl.tf).

**Comment by JafarAbdi** [comment]
Closing since those suggested changes got merged!
